# ECON622: Problem Set 1

Jesse Perla, UBC

## Student Name/Number: (doubleclick to edit)

## Question 1

Follow instructions in [Python Environment
Setup](../pages/python_setup.qmd) to get your python environment setup.

Some imported packages which will tell you if you have a successful
installation

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import pandas as pd
import torch
import jax
import jax.numpy as jnp
import jax.numpy as jnp
from jax import grad, hessian

Mess around with your setup until the following work

In [3]:
x = torch.zeros((2, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
x = jnp.zeros((2, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]

No need to get GPUs/etc. working. If you have issues on windows, see
[JAX
Installation](https://jax.readthedocs.io/en/latest/installation.html#cpu)
and [Pytorch Installation](https://pytorch.org/get-started/locally/)
instructions

## Question 2

This section just summarizes some reading on how JAX works, and asks you
to come up with some demonstrations of its functionality. Read:

-   [JAX
    Quickstart](https://jax.readthedocs.io/en/latest/notebooks/quickstart.html)
-   [JAX
    Basics](https://jax.readthedocs.io/en/latest/jax-101/01-jax-basics.html)
-   [JAX
    Jit](https://jax.readthedocs.io/en/latest/jax-101/02-jitting.html)
-   [JAX
    Vectorization](https://jax.readthedocs.io/en/latest/jax-101/03-vectorization.html)
-   [JAX
    AD](https://jax.readthedocs.io/en/latest/jax-101/04-advanced-autodiff.html)

### Question 2.1

Write a function which takes a normally distributed random number and
calculates the standard deviation manually (i.e. calculate the mean,
second moment, etc. manually and then form the standard deviation
yourself in the function)

Compile the function using the `jit` and the decorator `@jit`

In [5]:
# MODIFY HERE

### Question 2.2

Now take that function and generate a matrix of random normals and use
`vmap` to calculate the standard deviation across rows, then across
columns. Compare to `jnp.std(x, axis=0)` and `jnp.std(x, axis=1)`

In [6]:
# MODIFY HERE

### Question 2.3

Take the following code, and find the hessian of `f` at `x`

In [7]:
# MODIFY HERE

# Define a multivariate function
def f(x):
    return jnp.sum(x ** 2)

# Define a point at which to evaluate the function
x = jnp.array([1.0, 2.0, 3.0])